---
- hosts: 127.0.0.1
  connection: local
  vars: &vars
    myvar: "playbook_local"
  roles:
    - {role: none, <<: *vars }
    - {role: none, myvar: "playbook_role"}
    - {role: use_default, <<: *vars }
    - {role: use_default, myvar: "playbook_role"}
    - {role: use_var, <<: *vars }
    - {role: use_var, myvar: "playbook_role"}
    - {role: use_both, <<: *vars }
    - {role: use_both, myvar: "playbook_role"}
